code/solr/SolrIndex.php
tests/SolrIndexTest.php

This has been documented in the readme for ages but never implemented.
Tested with localsolr with highlighting enabled.
cc @hafriedlander

BUG Add missing addStoredFields method

---

code/solr/SolrIndex.php
tests/SolrIndexTest.php

Highlighting will simply be empty otherwise, presumably
because it can't match against the complex query term in the "q" parameter.

Fix highlight support when querying by fields (or boosting fields)

---

tests/BatchedProcessorTest.php

Fixes https://github.com/silverstripe-labs/silverstripe-fulltextsearch/issues/77
State is not being changed and restored robustly enough for this test to recover, so we simply omit subsites completely from this test.
The problem is likely due to `$illegalExtensions` option in `SapphireTest` not being able to properly restore removed extensions after the test is complete.
It's detrimental to force fulltextsearch tests to rely so heavily on a third party module so until we can fix the feature in core just don't let the tests fail.

BUG Prevent subsites breaking travis tests

---

conf/solr/4/templates/types.ss

New PR for https://github.com/silverstripe-labs/silverstripe-fulltextsearch/pull/42

adding stemming support

---

code/solr/Solr.php
code/solr/SolrConfigStore.php
docs/en/Solr.md

adding ability to define different port for WebDAV than used for Solr

---

code/solr/Solr.php
docs/en/Solr.md
docs/en/index.md

If somebody has more info on PHP timeout/abort behaviour in various web server implementations (mod_fcgi, mod_php, nginx, IIS), please add here.
cc @hafriedlander @tractorcow

Docs on index triggers, queues and timeouts

---

docs/en/Solr.md

Copied from CWP docs at https://www.cwp.govt.nz/guides/core-technical-documentation/common-web-platform-core/en/cwp-features/solr_search.
It's not specific to this platform, so should be part of the general docs.

Add docs on indexing dataobjects

---

code/search/SearchIndex.php
tests/SearchUpdaterTest.php
tests/SolrIndexTest.php

Index now supports multiple relations with the same name.

---

conf/solr/3/templates/types.ss
conf/solr/4/templates/types.ss

Move SynonymFilterFactory to bottom of analyzer to include synonyms in search results

---

README.md
code/search/indexes/SearchIndex.php
code/search/variants/SearchVariantVersioned.php
code/solr/Solr.php
code/solr/SolrIndex.php
code/solr/reindex/handlers/SolrReindexImmediateHandler.php
code/solr/tasks/Solr_BuildTask.php
docs/en/Solr.md
docs/en/index.md
tests/SolrIndexTest.php

Allows Solr_Configure task to run

FIX Replace Object reference with Injector and use ModuleLoader to resolve schema location

---

_config/processor.yml
src/Search/Processors/SearchUpdateCommitJobProcessor.php
src/Search/Processors/SearchUpdateQueuedJobProcessor.php
src/Solr/Reindex/Handlers/SolrReindexQueuedHandler.php
src/Solr/Reindex/Jobs/SolrReindexGroupQueuedJob.php
src/Solr/Reindex/Jobs/SolrReindexQueuedJob.php
src/Solr/Reindex/Jobs/SolrReindexQueuedJobBase.php
src/Utils/Logging/QueuedJobLogHandler.php
tests/BatchedProcessorTest.php
tests/BatchedProcessorTest/BatchedProcessor_QueuedJobService.php
tests/SolrReindexQueuedTest.php
tests/SolrReindexQueuedTest/SolrReindexQueuedTest_Service.php

FIX Update namespace references to Symbiote

---

src/Search/Variants/SearchVariant.php
src/Search/Variants/SearchVariant_Caller.php

API Make SearchVariant::call(...) arguments variadic

---

src/Solr/Tasks/Solr_Reindex.php

API Remove deprecated code

---

src/Solr/SolrIndex.php
tests/SolrIndexTest.php

NEW Support environment variables for Solr index prefix and suffix

---

src/Search/FullTextSearch.php
src/Search/Processors/SearchUpdateCommitJobProcessor.php
src/Search/Processors/SearchUpdateQueuedJobProcessor.php
src/Search/SearchIntrospection.php
src/Search/Updaters/SearchUpdater.php
src/Solr/Reindex/Handlers/SolrReindexQueuedHandler.php
src/Solr/Reindex/Jobs/SolrReindexGroupQueuedJob.php
src/Solr/Reindex/Jobs/SolrReindexQueuedJob.php
src/Solr/Reindex/Jobs/SolrReindexQueuedJobBase.php
src/Solr/SolrIndex.php
src/Utils/Logging/MonologFactory.php
src/Utils/Logging/QueuedJobLogHandler.php

Resolves #159 
Use namespace imports rather than fully qualified class names in strings

ENHANCEMENT Use namespace imports over fully qualified class names

---

src/Search/FullTextSearch.php
src/Search/SearchIntrospection.php

FIX Replace uppercase String occurrences with lowercase version ones

---

src/Solr/Services/SolrService.php
src/Solr/SolrIndex.php
tests/SolrIndexTest.php
tests/SolrReindexTest.php

NEW Replace backslashes in Solr index names with dashes

---

composer.json
src/Solr/Reindex/Handlers/SolrReindexImmediateHandler.php

NEW Use symfony/process to execute immediate system commands for reindexing

---

docs/en/index.md
src/Search/Updaters/SearchUpdater.php

NEW Allow autoconfigure to be disabled via configuration

---

composer.json

Add symbiote/silverstripe-queuedjobs to composer.suggests

---

src/Solr/Forms/SearchForm.php

Results in SearchForm did not take start GET var into account

fix missing pagination in search results

---

README.md
_config.php
code/search/SearchIndex.php
code/search/SearchUpdater.php
code/solr/Solr.php

Added php 7.2 support

---

src/Solr/Reindex/Handlers/SolrReindexBase.php

Fixes #270 
- Reset state to originalState when processing Variants / Groups

FIX: #270 - Reset variant state back to original state after processing

---

code/search/SearchIndex.php

A follow-up PR to replace #240.
As SS 3.7.x doesn't have a defined EOL yet and will be in limited support for at least another year, I think it's still worth considering this fix even for the `2` branch.

FIX #108 for SS 3.x - Update and simplify getDirtyIDs method

---

src/Search/Indexes/SearchIndex.php

A follow-up PR to replace #239. The tests are now green and I will test it in our project.
Thanks for the pointers @UndefinedOffset and @tractorcow!

FIX #108 - Update and simplify getDirtyIDs method

---

src/Solr/SolrIndex.php

FIX: Always store the default field to support highlighting

---

.travis.yml
composer.json
phpunit.xml.dist
tests/BatchedProcessorTest.php
tests/SearchUpdaterTest.php
tests/SearchVariantSubsitesTest.php
tests/SearchVariantVersionedTest.php
tests/SearchableServiceTest.php
tests/SolrIndexSubsitesTest.php
tests/SolrIndexTest.php
tests/SolrIndexVersionedTest.php
tests/SolrReindexQueuedTest.php
tests/SolrReindexTest.php
tests/SolrWritersTest.php

Issue https://github.com/silverstripe/silverstripe-framework/issues/10019

API phpunit 9 support

---

src/Search/Indexes/SearchIndex.php

Issue https://github.com/silverstripe/silverstripe-fulltextsearch/issues/302

FIX Allow deprecated warnings

---

composer.json

Cherry pick of https://github.com/silverstripe/silverstripe-fulltextsearch/pull/312

[Backport] Symfony process constructor fix (#312)

---

composer.json

Issue https://github.com/silverstripe/silverstripe-framework/issues/10250

DEP Use silverstripe fork

---

composer.json

Issue https://github.com/silverstripe/silverstripe-framework/issues/10294

DEP Require proxy-db ^1
