silverstripe/silverstripe-fulltextsearch

_config/config.yml, code/search/SearchUpdater.php, code/solr/Solr.php
This should be amazing for people who like being able to trigger a reindex from the web, or those with lots of content they'd prefer that queuedjobs ran.
@hafriedlander please review that my doing exactly as you directed was the right solution. :)
I've done a few tests locally, both with the queuedjobs updater as well as the direct updater.
=> API Solr_Reindex uses configured SearchUpdater instead of always doing a direct write

code/search/SearchUpdater.php
Stopped indexing of classes which were unrelated to overall variants.
For example, an index with excludeVariantState(array('SearchVariantVersioned' => 'Stage'))
should only set this variant state on types where appliesTo() returns true, namely "Page".
Without the $class parameter it also returned on "File" index requests,
which then lead to all index requests being discarded later on somewhere in SearchUpdater.
Regression introduced in 625d282.
cc @tractorcow
=> Regression in SearchUpdater_ObjectHandler

code/search/FullTextSearch.php, code/search/SearchIndex.php, code/search/processors/SearchUpdateBatchedProcessor.php, code/search/processors/SearchUpdateCommitJobProcessor.php, code/search/processors/SearchUpdateQueuedJobProcessor.php, docs/en/index.md, tests/BatchedProcessorTest.php
Oh my good, look at this pull request. It's so amazing!
What have I done! On a coffee-less afternoon nonetheless?
- Indexes can finally hide other indexes. This is useful when you don't want classes to be indexed, but they could be in a third party module you don't want to edit. (see docs below) This in itself is a great performance increase, but no longer do you need to have solr indexing work done on indexes you don't want to maintain.
- SolrIndex::commit has been split into a separate queued job which is added to the queue once an update job has been completed. This is useful if you want to run multiple update jobs in a sequence, but don't want to run into the dreaded `exceeded limit of maxWarmingSearchers=X` error.
It also nicely bunches several smaller updates into a single commit, …
=> API Separate searchupdate / commit into separate queued-jobs

code/solr/SolrIndex.php, conf/solr/4/templates/schema.ss, docs/en/Solr.md, tests/SearchVariantVersionedTest.php, tests/SolrIndexTest.php
Although you can already specify boosting (with some effort) at the time of query, it can be a lot more convenient to specify specific boosts on individual fields when declaring your index schema.
Includes tests and documentation!
Note that `$extra_options['boost']` actually crashes solr, so although we give a consistent interface, we actually need to intercept that custom option internally.
=> API Enable boosted fields to be specified on the index

code/solr/Solr.php, code/solr/SolrIndex.php, conf/solr/4/extras/solrconfig.xml
Default config has been fixed (previously would crash on references to name and text fields, when we should use the _text field consistently).
uploadConfig has been refactored out of Solr_Configure into SolrIndex, so that specific indexes can have control over additional files (e.g. synonyms.txt) that are necessary.
Issues with parsing of collation results from solr have been resolved. If the collation result is an object, the suggestions are parsed in turn until a suggestion is returned.
=> API Support custom files / spelling correction

code/solr/SolrIndex.php, conf/solr/4/templates/types.ss, docs/en/Solr.md
This means that if we want to copy all fields to another, we can do it in one place, rather than having an explicit copy for each additional source / destination pair.
Also adds additional textSpellHtml type for html-safe spelling database generation. The default spellcheck field didn't do HTML cleaning so wasn't very safe.
=> API Additional support for custom copy_fields

_config.php, _config/processor.yml, code/search/SearchVariant.php, code/search/SearchVariantSiteTreeSubsitesPolyhome.php, code/search/SearchVariantVersioned.php, code/solr/Solr.php, code/solr/SolrIndex.php, code/solr/reindex/handlers/SolrReindexBase.php, code/solr/reindex/handlers/SolrReindexHandler.php, code/solr/reindex/handlers/SolrReindexImmediateHandler.php, code/solr/reindex/handlers/SolrReindexMessageHandler.php, code/solr/reindex/handlers/SolrReindexQueuedHandler.php, code/solr/reindex/jobs/SolrReindexGroupQueuedJob.php, code/solr/reindex/jobs/SolrReindexQueuedJob.php, code/solr/reindex/jobs/SolrReindexQueuedJobBase.php, code/utils/logging/MonologFactory.php, code/utils/logging/QueuedJobLogHandler.php, code/utils/logging/SearchLogFactory.php, composer.json, docs/en/Solr.md, tests/SolrReindexQueuedTest.php, tests/SolrReindexTest.php
This also has incremental deletion of records; Rather than deleting all records in solr up front, it'll simply delete all records that it KNOWS won't exist up front, and then deletes all other records incrementally in batches.
Each batch is derived using the formula `ID % total_groups = this_group`. This means that batches don't need to store a list of IDs for each record, and copes with cases where ids may not be contiguous, as well as deleted IDs that may not have a local record anymore.
Re-index is broken into a base implementation, with separate subclasses for each implementation (including immediate reindex for local, message queue and queuedjobs).
`Solr_Reindex`, two queued jobs, a new logging API, and several tests have been added.
Part of the logic for generating SOLR query syntax …
=> API QueuedJob support for Solr_Reindex

tests/SolrIndexTest.php, tests/SolrIndexVersionedTest.php, tests/SolrReindexQueuedTest.php, tests/SolrReindexTest.php
PHPUnit now includes matching functions like `any()` and `anything()` outside of a namespace, which conflicts with `Phockito` that does the same thing when calling `Phockito::include_hamcrest(true)`.
This test in particular breaks Behat, because the file includes a class (`SolrReindexTest_Item`) that extends `DataObject`, meaning that this file gets included very early in the initialisation process.
Instead, we can just set `Phockito::include_hamcrest(false)` and use the full path to the Hamcrest matching functions instead (e.g. `\Hamcrest_Matchers::anything()`).
=> MINOR: Don't include Hamcrest globally so it doesn't conflict with PHPUnit

code/search/SearchUpdater.php, tests/BatchedProcessorTest.php, tests/SearchUpdaterTest.php, tests/SearchVariantVersionedTest.php, tests/SolrIndexTest.php, tests/SolrIndexVersionedTest.php
Fixes some regressions in recent framework fixes to versioned.
Also remove unnecessary config nesting in tests which are now handled via core.
Fixes issue I mentioned at https://github.com/silverstripe-labs/silverstripe-fulltextsearch/pull/109#issuecomment-189010025
cc @dhensby , sorry it's late!
=> BUG Fix versioned writes where subtables have no fields key

code/search/SearchIndex.php
When using derived fields subsequent iterations of the loop on [line 527](https://github.com/silverstripe-labs/silverstripe-fulltextsearch/blob/master/code/search/SearchIndex.php#L527) can in some cases be reset to an id that is not the one being re-indexed resulting in a SQL error.
=> BUGFIX: Fixed issue where the $id variable would be overridden in derived fields

.travis.yml, code/search/SearchIndex.php, code/search/SearchVariant.php, code/search/SearchVariantSiteTreeSubsitesPolyhome.php, code/search/SearchVariantSubsites.php, code/search/SearchVariantVersioned.php, code/solr/Solr.php, code/solr/SolrIndex.php, tests/SolrIndexSubsitesTest.php, tests/SolrIndexSubsitesTest.yml, tests/SolrIndexVersionedTest.php, tests/SolrReindexTest.php
Plus lots of other fixes:
- Fixed more than one versioned object in an index
- Fixed more than one subsites object in an index
- Fixed SearchVariantSubsites ending up with unflushable (and often invalid) caches of subsites during write
- Fix empty catch blocks from hiding errors during testing
- Add missing abstract alterDefinition to SearchVariant.
- Fix variants assuming that origin === base class for each object type added
=> BUG fix issues with search variants applying to more than one class

code/search/SearchUpdater.php
When the database isn’t yet created, $current is set, but
$current->currentDatabase() is empty. I suspect this only applies to 
PDO connections. It results in errors during startup.
This check fixes it.
=> FIX: Fix initial dev/build on PDO Database.

code/solr/SolrIndex.php, docs/en/Solr.md
Often I find myself copying the entire search() function from SolrIndex into my custom index classes, so that I can pull some extra information from the solr-php-client into the templates.
I've included some docs on how to use this extension point to add faceting, a common use case.
This change didn't seem to need tests.
=> Add an extension hook to allow altering search results

code/search/SearchIndex.php
When using derived fields if the ids returned from the previous iteration of the [chain loop](https://github.com/silverstripe-labs/silverstripe-fulltextsearch/blob/master/code/search/SearchIndex.php#L547-L560) is empty an SQL error will occur due to the ``IN()`` statement being empty. This pull request simply breaks out of the loop when ``$ids`` is empty.
=> BUGFIX: Fixed crash when the relationship has no parents

tests/SolrIndexVersionedTest.php
When Phockito is not installed the SolrVersionedTest_Index causes an invalid argument exception to be thrown. Stating "Can't add classes which don\'t have data tables (no $db or $has_one set on the class)". This appears to be caused by the return in SolrIndexVersionedTest.php inside of a check for the Phockito class. Moving the SolrIndexVersionedTest_Object class above that check stops the exception. This pull request does that.
=> BUGFIX: SolrVersionedTest_Index causing crash in unit tests when Phockito is not installed

code/solr/SolrIndex.php
Previously these headers were set on dev and test environments, but not live.
Now, they will only be set on dev environments. You can always use `?isDev=1` to force a test or live environment into dev mode (with appropriate permissions).
There's no reason why test should show these headers but live shouldn't - the two envs should be treated the same in this case (otherwise you get security auditors pointing out this 'flaw' which never affects production).
Credit to @timkung who had done this on an earlier version of the module, but the PR was made against the wrong base repository so it never got merged :)
=> Remove X-Query, X-Filters, and X-QueryFields headers from being set

code/solr/SolrIndex.php, code/solr/reindex/handlers/SolrReindexImmediateHandler.php, code/solr/reindex/handlers/SolrReindexQueuedHandler.php
This means the same code can run on a single solr core and have the same indexes but use prefixes or suffixes to keep them separate
=> adding ability for solr suffix and prefixing

conf/solr/4/templates/types.ss
Porter Stemming is causing synonyms to respond incorrectly and provide skewed results. Removing Porter Stemming from default template allows functionality to work out of the box.
Stemming can be added by client by replacing type.ss template if required.
=> Remove Porter Stemming from default template

README.md, code/search/SearchVariantSubsites.php, tests/SearchVariantSubsitesTest.php
When attempting to do this in project code, SearchVariantSubsites kicks in and replaces any filter you've applied with the current subsite ID, which prevents you from searching for filtered results in another subsite.
This fix prevents the module from doing this if a filter is already applied on the query
=> Obtain search results for a particular subsite when the request comes from a query

code/solr/Solr.php
=> FIX Return a non-zero exit code when Solr_Configure has an exception

.travis.yml
Tests for PHP 5.3 are failing, and is no longer supported anyway.
```
5.3 is not pre-installed; installing
Downloading archive: https://s3.amazonaws.com/travis-php-archives/binaries/ubuntu/14.04/x86_64/php-5.3.tar.bz2
0.06s$ curl -s -o archive.tar.bz2 $archive_url && tar xjf archive.tar.bz2 --directory /
bzip2: (stdin) is not a bzip2 file.
tar: Child returned status 2
tar: Error is not recoverable: exiting now
$ phpenv global 5.3
rbenv: version `5.3' not installed
```
=> Remove PHP 5.3 tests as 5.3 is now unsupported.

code/search/processors/SearchUpdateCommitJobProcessor.php
Related issue:
https://github.com/silverstripe/silverstripe-fulltextsearch/issues/151
Currently in `SearchUpdateCommitJobProcessor`:
```php
/**
* List of dirty indexes to be committed
*
* @var array
*/
public static $dirty_indexes = true;
```
This results in many Warning being thrown as `$dirty_indexes` is used (from what I could see) exclusively as type `array`, not `boolean`.
EG:
```
#0 in_array() expects parameter 2 to be array, boolean given:: called at [/sites/statsunleashed/releases/20170811014625/fulltextsearch/code/search/processors/SearchUpdateCommitJobProcessor.php:217]
```
=> Set SearchUpdateCommitJobProcessor::$dirty_indexes default to array, not bool. Fixes #151

code/solr/Solr.php
Adding extension hooks before and after Solr_Configure and Solr_Reindex tasks to allow other modules (e.g. Translatable) to modify filters consistently across multiple task iterations.
Addressing issue #154.
=> Adding extension hooks before and after Solr tasks

src/Solr/Services/SolrService.php
This fixes a bug when running Solr_Configure with a core that is already configured.
Without this fix, Solr responds with an HTTP 500, because `Solr_Configure` thinks the core isn't active, and attempts to create it (which causes Solr to respond with `Core with name 'ShortClassName' already exists`).
The issue is because Solr stores the full core name (e.g. `Mysite\Search\SolrIndex`), but references it internally and via the API via the class short name (`SolrIndex` in this example).
Note: I haven't gotten this all the way to actually search a Solr core yet, so not sure if there are other namespace issues that I've yet to run into here.
=> FIX: coreIsActive() failed when using a namespaced core

src/Solr/SolrIndex.php
Before:
```php
$query->exclude(SiteTree::class . '_ShowInSearch', 0);
```
Result:
```
936953 [qtp2081303229-16] ERROR org.apache.solr.core.SolrCore  – org.apache.solr.common.SolrException: undefined field SilverStripeCMSModelSiteTree_ShowInSearch
```
Fix double escapes namespace separators in PHP class names when using them in `->exclude()` keys.
=> FIX Double escape namespace separators in class names when excluding fields

src/Search/Queries/SearchQuery.php, src/Solr/SolrIndex.php
=> FIX Double escape namespace separators in class names when boosting fields

_config/tests.yml, src/State/FullTextSearchTestState.php
This was put into the tests namespace unintentionally but should live in the main module code
=> API More TestState into source folder from tests

src/Solr/Reindex/Handlers/SolrReindexImmediateHandler.php
It appears that when executing in a Microsoft Windows environment the
default shell used in the immediate reindex handler is CMD, which has
some severely different syntax support from that of a POSIX machine (e.g.
GNU bash). This leads to errors to do with double escaping certain
parameters passed in via the CLI - culminating in an Injector error about
an non-extant class e.g. `SilverStripe\\CMS\\Model\\SiteTree` - two
slashes a namespace separator does not make!
=> FIX permit reindexing on a Windows machine

src/Search/Indexes/SearchIndex.php
Knowing if a DataObject has a table or not is irrelevant - data is queried
out and pushed into solr all the same, whether there is a join table, a
base table, or any combination with maybe a few no-tables in between.
SomeDataClass::get() will fetch all data irrelevant of tables, that's the
point of an abstraction like SilverStripe's ORM.
The index featured is a default install, where `Page` is defined as
```php
use SilverStripe\CMS\Model\SiteTree;
class Page extends SiteTree
{
}
```
and defines an index [adding only `Page::class` to it](https://github.com/dnadesign/silverstripe-elemental/blob/master/src/Search/ElementalSolrIndex.php#L20).
Resolves #168
=> FIX Don't assume a DataObject's table.

src/Search/Variants/SearchVariant.php, src/Solr/SolrIndex.php, tests/SolrIndexTest.php
This pull request is an option for how we could address #33 - it adds a new method `SearchVariant::withCommon` which will return an array of search variants that are relevant to at least one of the classes given. SolrIndex can use this to provide either the classes in the index, or the classes specified for the query by user code.
This is different from `SearchVariant::with` which will apply all variants that are relevant to the environment if you don't provide it a specific class name (which `SolrIndex::search` does with a standard query). I believe this is what is causing #33, at least for me.
The unit test fix is actually an example of the bug, since `SearchUpdaterTest_Container` is not versioned so the versioned state is not relevant to it.
=> NEW Add SearchVariant::withCommon to run callbacks on relevant variants rather than all

src/Search/Indexes/SearchIndex.php
In previous versions one could add e.g. a filter field for their index to
a relationship, such as 'Categories.ID' where categories is a many_many
relationship. This stopped working in the SS4 upgrade. Namespaces, whoop.
Resolves #205
=> FIX Reenable indexing of relationship fields

.scrutinizer.yml, _config/database.yml, composer.json, src/Search/Captures/SearchManipulateCapture_MySQLDatabase.php, src/Search/Captures/SearchManipulateCapture_PostgreSQLDatabase.php, src/Search/Captures/SearchManipulateCapture_SQLite3Database.php, src/Search/Extensions/ProxyDBExtension.php, src/Search/Updaters/SearchUpdater.php
This PR makes use of Damian's proxy module https://github.com/tractorcow/silverstripe-proxy-db, which allows the registration of a shared proxy database that multiple modules can decorate.
It fixes #201. 
**Important**: It appears that proxydb can't be used with _any_ other database proxy. This means it relies on https://github.com/silverstripe/silverstripe-auditor/issues/16 being resolved. It currently works with the changes made in https://github.com/lekoala/silverstripe-debugbar/commit/b56a8ed22fa83478246c77522786ff55841d3d52.
Deprecation notices were added in the expectation to introduce these changes in  3.1.0
=> NEW Update to use proxied DB instead of self-proxied

_config.php, docs/en/Solr.md, docs/en/index.md, src/Search/Queries/SearchQuery.php, src/Search/Queries/SearchQuery_Range.php, src/Search/Variants/SearchVariant.php, src/Search/Variants/SearchVariantSubsites.php, tests/SearchVariantSubsitesTest.php, tests/SolrIndexTest.php, tests/SolrReindexQueuedTest.php, tests/SolrReindexTest/SolrReindexTest_Variant.php
Updated port of https://github.com/silverstripe/silverstripe-fulltextsearch/pull/64/ to improve readability and usability of the `SearchQuery` API.
=> clean up SearchQuery API

_config/config.yml, docs/en/index.md, src/Search/Updaters/SearchUpdater.php, src/Solr/Control/ContentControllerExtension.php, src/Solr/Forms/SearchForm.php, templates/Layout/Page_results_solr.ss
Assume that if we have installed the module, we want the `$SearchForm` to use Solr, not the `FulltextSearch::enable()` version.
Will add docs shortly - and this is a very basic implementation, to be used as a jumping off point mostly I think.
=> Replace default CMS SearchForm with Solr version

.travis.yml, phpcs.xml.dist, tests/SolrReindexQueuedTest.php, tests/SolrReindexQueuedTest/SolrReindexQueuedTest_Service.php, tests/SolrReindexTest.php
This will test fulltextsearch across multiple core versions in Travis, and also stops relying on the framework phpcs ruleset (added to gitattributes as export-ignore in later versions).
I'll raise a separate issue to implement further PSR-2 compliance changes.
=> Add different core installer versions to Travis matrix and add own phpcs ruleset

bin/fulltextsearch_quickstart, composer.json, docs/en/index.md, docs/examples/daemon_script, docs/examples/default_index.php.example
Pulled out from #215 
Simplifies installation on a (yum- , dnf- or apt-ready) dev server to be:
```bash
composer require silverstripe/fulltextsearch && vendor/bin/fulltextsearch_quickstart
```
=> add quickstart script into vendor/bin

src/Search/Indexes/SearchIndex.php
Resolves #222 
This reduces the log level. Unfortunately the method name is still `warn` which could be considered inconsistent but I didn't want to change the API.
=> FIX Reduce log level so errors do not automatically output

_config/config.yml, docs/en/00_index.md, docs/en/04_querying.md, src/Search/Adapters/SearchAdapterInterface.php, src/Search/Adapters/SolrSearchAdapter.php, src/Search/Criteria/SearchCriteria.php, src/Search/Criteria/SearchCriteriaInterface.php, src/Search/Criteria/SearchCriterion.php, src/Search/Queries/AbstractSearchQueryWriter.php, src/Search/Queries/SearchQuery.php, src/Solr/SolrIndex.php, src/Solr/Writers/SolrSearchQueryWriterBasic.php, src/Solr/Writers/SolrSearchQueryWriterIn.php, src/Solr/Writers/SolrSearchQueryWriterRange.php, tests/SolrWritersTest.php
Currently in `fulltextsearch` we can `filter` and we can `exclude`, but both of these are "single level", in that you cannot group filters with combinations of `AND` and `OR` statements.
In order to allow for more complex filtering, I have implemented criterion objects. These objects can be joined and grouped in any number of ways - allowing you to achieve any kind of nested filter that you might want.
* **`SearchCriteriaInterface`**: Interface for `SearchCriterion` and `SearchCriteria` classes.
* **`SearchCriterion`**: An object containing a single field filter (target field, comparison value, comparison type).
* **`SearchCriteria`**: An object containing a collection of `SearchCriterion` and/or `SearchCriteria` with conjunctions (IE: `AND`, `OR`) between each.
* **`SearchQueryWriter`**: …
=> Add nested filtering via Criteria and Criterion objects.

src/Search/Variants/SearchVariantVersioned.php
This is the last usage of a deprecated method left in this module. Additionally, the last across all supported modules (at least in terms of CWP) that I can seem to find.
Fixes silverstripe/cwp-recipe-search#6
=> Removing use of deprecated method

_config/config.yml
Fixes #231.
Initially added in 7b78a84 and removed in e08731d but was intended to be added back in once #216 was merged from what I can tell.
=> Add ContentControllerExtension back

src/Solr/Reindex/Handlers/SolrReindexImmediateHandler.php
Currently SolrReindexImmediateHandler will die after 60 seconds, as that is the default timeout in Symfony\Component\Process\Process. This will allow that to be overridden via Config
=> Update Process timeout via Config

src/Search/Variants/SearchVariant.php
Re-add the option to use numerically indexed arrays of classes in `withCommon` method, similar to what `with` method allowed.
=> FIX #241 - Support numerically indexed array of classes

src/Solr/Solr.php, src/Solr/Stores/SolrConfigStore_Post.php, src/Solr/Tasks/Solr_Configure.php
This copies the `CwpSolrConfigStore` ([from here](https://github.com/silverstripe/cwp-search/blob/master/src/Solr/CwpSolrConfigStore.php)) in to the fulltextsearch module. If merged that file can be removed from the cwp-search module and the mode set to 'post' in `CwpSolr.php`
The CWP solrproxy which receives the solr configuration files via POST is going to be used on SSP also. This requires the application to configure a config store which does a POST to send through the files. As this config store is not strongly tied to the CWP solr proxy, just an endpoint that requires a POST I think it is generic enough to put in this module. This will mean users of solr on SSP will not need to install CWP modules to use solr.
=> Adds a 'post' option for solrconfigstore

_config/config.yml, docs/en/01_getting_started.md, src/Search/Extensions/DisableIndexingOnFileMigration.php, tests/DisableIndexingOnFileMigrationTest.php
This PR disables indexing when the file migration is doing its thing.
It shouldn't break if the MigrateFIleTask is not at it's expected spot or if the extension points hasn't been implemented in the project's framework version.
(I've never done anything to fulltextsearch before, so don't assume I know what I'm doing, because I don't.)
* https://github.com/silverstripe/silverstripe-framework/issues/8965
=> Disable indexing on file migration

.gitattributes
Make docs available in composer require without preferring source to ensure vendor/bin/fulltextsearch_quickstart script has access to the files it needs and users have docs available available locally.
=> Make docs available without --prefer-source

.travis.yml, src/Solr/Stores/SolrConfigStore_Post.php
During [the port of `CWPSolrConfigStore_Post` to this module](https://github.com/silverstripe/silverstripe-fulltextsearch/pull/246), the `remotepath` config was made mandatory by way of a dropped existence check. This made the store incompatible with CWP, where a `remotepath` is not set.
This PR reinstates the previous check, thereby fixing support for CWP and other environments like it.
=> FIX Make remotepath optional to restore compatibility with CWP

.travis.yml, README.md, _config.php, code/search/SearchIndex.php, composer.json
`create_function()` is deprecated, causing unit test failures in PHP 7.2
=> NEW Bump minimum PHP to 7.1, SilverStripe to 3.7, replace PHP 7.2 incompatible code

src/Search/Variants/SearchVariant.php, src/Search/Variants/SearchVariantSubsites.php
Allows people to opt-in different classes to the subsites SearchVariant to ensure objects are indexed correctly.
=> ENHANCEMENT Add extension point to appliesTo for SearchVariantSubsites

src/Search/Processors/SearchUpdateQueuedJobProcessor.php
getJobType method returns null as querying a string rather than a namespaced class.
=> FIX: SearchUpdateQueuedJobProcessor JobType NULL

src/Search/Updaters/SearchUpdater.php
One of the 3->4 update commits (6066af5841fd1df21ef32ff3fa089c6e48ea4f26) replaced `SearchUpdateProcessor` with `SearchUpdateImmediateProcessor`, but that means that the existing processor yml fails to replace the `SearchUpdateImmediateProcessor` with `SearchUpdateQueuedJobProcessor`  as I think is intended?
c.f https://github.com/silverstripe/silverstripe-fulltextsearch/blob/3/_config/processor.yml#L19
=> FIX: allow update processor to be overridden by existing yml

.travis.yml, composer.json, docs/en/03_configuration.md, src/Search/Processors/SearchUpdateProcessor.php, src/Search/Services/IndexableService.php, src/Solr/Forms/SearchForm.php, src/Solr/Reindex/Handlers/SolrReindexBase.php, src/Solr/SolrIndex.php, tests/IndexableServiceTest.php, tests/SolrIndexTest.php, tests/SolrIndexTest/SolrIndexTest_MyDataObjectOne.php, tests/SolrIndexTest/SolrIndexTest_MyDataObjectTwo.php, tests/SolrIndexTest/SolrIndexTest_MyPage.php, tests/SolrIndexTest/SolrIndexTest_ShowInSearchIndex.php, tests/SolrReindexTest.php
**This was originally branched off 3.6, have since rebased and retargeted to 3**
Issue: https://github.com/silverstripe/silverstripe-fulltextsearch/issues/257
**Inlet filtering - cms save**
SearchUpdateProcessor.php
**Inlet filtering - solr reindex**
SolrReindexBase.php 
**Outlet filtering**
SolrIndex.php
=> Filter DataObjects on ShowInSearch

docs/en/01_getting_started.md
Minor tweak to the doc to use the correct executable name in the getting started doc.
=> DOC Use the correct name for the executable in the getting started doc

src/Search/Queries/SearchQuery_Range.php
[The docs](https://github.com/silverstripe/silverstripe-fulltextsearch/blob/3/docs/en/04_querying.md#searching-value-ranges) indicate that this class should be injectable.
=> Make SearchQuery_Range injectable.

src/Solr/Stores/SolrConfigStore_File.php, src/Solr/Stores/SolrConfigStore_Post.php, src/Solr/Stores/SolrConfigStore_WebDAV.php
Previously the `isset` check would still allow falsey values.
Fix for #260. It's quite possible the module won't get too much longterm love going forward but this could be seen as maintenance to allow for configurations where these settings are set to null but still incorrectly applied.
=> FIX Only use values that are not empty

composer.json, src/Solr/Reindex/Handlers/SolrReindexImmediateHandler.php
Issue https://github.com/silverstripeltd/product-issues/issues/492
=> DEP Allow symfony 4

src/Utils/WebDAV.php
Without this change, the error message isn't that helpful
`Got error from webdav server - 0`
With this change, the error message is more suggestive:
`Got error from webdav server - Failed to connect to cc4f1a92edc7f330 port 80: Connection refused`
=> ENH Show error message instead of error code on WebDAV check

composer.json, src/Utils/WebDAV.php
I noticed that the curl handles are not closed after use, which means (in older versions of PHP) that the resources are not released potentially leading to memory leaks.
Changes:
- Add `ext-curl` dep to compsoer file
- remove unsued variable declarations
- closed curl handles after use
=> Close curl handles after use

src/Search/Services/SearchableService.php
Fixes #304 
See also silverstripe/silverstripe-elemental#951
Because there is no return value typehinting in DataObject::canView, the value returned from that method can be of any type. We must cast to boolean before returning the value to avoid possible errors with non-boolean return types.
=> FIX Don't assume DataObject::canView always returns bool

composer.json, src/Solr/Reindex/Handlers/SolrReindexImmediateHandler.php
This pull  requests bumps the symfony/process minimum version from 3.2 to 3.4 which allows the commandline param to be a array or a string.
Also implements fixes from @GuySartorelli
=> Symfony process constructor fix

src/Solr/Reindex/Handlers/SolrReindexImmediateHandler.php
Previously the executable, the PHP script and the task were a single string which `symfony/process` tried to wrap in apostrophes which subsequently failed as an invalid executable with error code 127 "command not found".
When each part of the command including the php, the CLI script and the task name, is passed in separately, the process does escape it correctly.
=> [Backport] Let symfony/process escape each command part separately

src/Solr/Reindex/Handlers/SolrReindexImmediateHandler.php
Symfony now escapes each component separately.
See https://github.com/silverstripe/silverstripe-fulltextsearch/issues/311
=> Don't double-escape state field

src/Search/Processors/SearchUpdateProcessor.php
When using the TestSession with behat on a project while silverstripe-fulltextsearch is installed, the following chain of events happens
- Temporary database used by TestSession is destroyed
- PHP shuts down
- The following is run, which was defined in FullTextSearch - SearchUpdater.php
- `register_shutdown_function(array(SearchUpdater::class, "flush_dirty_indexes"));`
- `flush_dirty_indexes` will eventually call `SearchUpdateProcessor::process()` - which will do a bunch of DB queries
- however there's no database, which triggers `No database selected` errors
=> FIX Ensure DB is active before processing

conf/solr/4/extras/solrconfig.xml, docs/en/06_troubleshooting.md
This is required in situations where autoCommit.openSearcher is set to "false",
and you don't want to rely on core restarts to make committed index updates available to new searches.
It's already configured like this in the Common Web Platform environments,
so this change will mainly affect other environments (such as Silverstripe Platform).
To opt out of this new behaviour, set up a custom solrconfig.xml.
More details in https://github.com/silverstripe/silverstripe-fulltextsearch/issues/274
=> NEW Ensure commits are visible to seachers (fixes #274)

composer.json
Was originally added [here](https://github.com/silverstripe/silverstripe-fulltextsearch/pull/322) which went into 3.10.1
Looks like this was accidentally reverted on merge-up https://github.com/silverstripe/silverstripe-fulltextsearch/compare/3.10.1...3.11.0
Tag 3.11.1 on merge
=> DEP Require proxy-db ^1

tests/BatchedProcessorTest.php
Issue https://github.com/silverstripe/gha-ci/issues/37
Might fix https://github.com/silverstripe/recipe-solr-search/runs/7459144288?check_suite_focus=true#step:12:69
`1) SilverStripe\FullTextSearch\Tests\BatchedProcessorTest::testBatching
Failed asserting that 15 matches expected 9.`
Don't need to release, though ensure is merged all the way up as recipe-solr-search uses x-dev branches
=> MNT Fix unit test
